#pragma once

enum DLL_PROCESS_TYPE
{
	DLL_PROCESS_GET_NONE = 0xFFFFFF00,
	DLL_PROCESS_GET_PROCEDURE,
	DLL_PROCESS_GET_DATA,
	DLL_PROCESS_INSTALL_VK_PRINT_HOOK,
	DLL_PROCESS_RELEASE_PROCEDURE,
	DLL_PROCESS_RELEASE_DATA,
	DLL_PROCESS_UNINSTALL_VK_PRINT_HOOK,
	DLL_PROCESS_TYPE_COUNT
};
enum FSP_EXTRET_TYPE
{
	FSP_EXTRET_FALSE = 0xffffffe0,
	FSP_EXTRET_TRUE = 0xffffffe1,
	FSP_EXTRET_VALUE_FALSE = 0xffffffe2,
	FSP_EXTRET_VALUE_TRUE = 0xffffffe3,

	FSP_EXTRET_DEFAULT = 0xfffffff0,
	FSP_EXTRET_BYPASS = 0xfffffff1,
	FSP_EXTRET_BLOCK = 0xfffffff2,
	FSP_EXTRET_BLOCK_PARAM = 0xfffffff3,
	FSP_EXTRET_VALUE = 0xfffffff4,
	FSP_EXTRET_VALUE_PARAM = 0xfffffff5,
	FSP_EXTRET_CONTINUE = 0xfffffff6,
	FSP_EXTRET_CONTINUE_PARAM = 0xfffffff7,
};

typedef struct _FSP_EXTENSION_PARAM
{
	DWORD_PTR dwParam1;
	DWORD_PTR dwParam2;
	DWORD_PTR dwParam3;
	DWORD_PTR dwParam4;
	DWORD_PTR dwParam5;
	DWORD_PTR dwParam6;
	DWORD_PTR dwParam7;
	DWORD_PTR dwParam8;
	DWORD_PTR dwParam9;
	DWORD_PTR dwParam10;
	DWORD_PTR dwParam11;
	DWORD_PTR dwParam12;
	DWORD_PTR dwParam13;
	DWORD_PTR dwParam14;
	DWORD_PTR dwParam15;
	DWORD_PTR dwParam16;
	DWORD_PTR dwParam17;
	DWORD_PTR dwParam18;
	DWORD_PTR dwParam19;
	DWORD_PTR dwParam20;
} FSP_EXTENSION_PARAM, * PFSP_EXTENSION_PARAM, * LPFSP_EXTENSION_PARAM;